#ifndef __TANG_FUNDAMENTAL_TYPES__
#define __TANG_FUNDAMENTAL_TYPES__

enum Tang_Fundamental_Type
{
    TANG_FTYPE_UNSET,
    TANG_FTYPE_C,
    TANG_FTYPE_UNKNOWN,
    TANG_FTYPE_ALIAS,
    TANG_FTYPE_FORM,
    TANG_FTYPE_CLASS,
    TANG_FTYPE_UNION,
    TANG_FTYPE_INT8,
    TANG_FTYPE_UINT8,
    TANG_FTYPE_INT16,
    TANG_FTYPE_UINT16,
    TANG_FTYPE_INT32,
    TANG_FTYPE_UINT32,
    TANG_FTYPE_INT64,
    TANG_FTYPE_UINT64,
    TANG_FTYPE_FLOAT32,
    TANG_FTYPE_FLOAT64
};

#endif
